// Starting data for the three characters. The DM's "Load characters" button inserts these once.
window.SEED = [
{slug:"malakor",name:"Malakor Vane",portrait_path:"images/malakor.jpg",own:"me",
live:{hp:17,thp:0,slots:[0,0],hh:0,insp:0,ds:[0,0],cond:""},
sheet:{
header:{cls:"Warlock 2",species:"Variant Aasimar",bg:"Haunted One",xp:700,player:"Chris"},
ab:{str:8,dex:13,con:14,int:10,wis:13,cha:17},pb:2,saves:["wis","cha"],
skills:["Arcana","Deception","Intimidation","Survival"],
combat:{hp:17,ac:12,init:1,speed:"30 ft.",hd:"2d8",senses:"Darkvision 60 ft."},
defenses:"Resistant to necrotic and radiant damage",
prof:{armor:"Light armor",weapons:"Simple weapons",langs:"Abyssal, Celestial, Common, Elvish"},
std:"Attack, Magic, Dash, Disengage, Dodge, Help, Hide, Ready, Search, Utilize, Opportunity Attack, Grapple, Shove, Improvise, Two-Weapon Fighting, Interact with an Object, Study, Influence",
acts:[["Healing Hands","1 / long rest. Action: touch a creature and restore 2 hit points."],["Pact of the Chain","When you take the Attack action you may forgo one attack so your familiar attacks with its reaction."],["Magical Cunning","1 / long rest. A one-minute rite regains up to 1 expended Pact slot."]],
atk:[["Chill Touch","+5","1d10 Necrotic","V/S"],["Eldritch Blast","+5","1d10+3 Force","V/S"],["Unarmed Strike","+1","0 Bludgeoning",""]],
feats:[["Core Warlock traits","Warlock","Pact Magic slots, Eldritch Invocations and the class's core rules (PHB 2024 p.153)."],["Agonizing Blast","Invocation","Adds your Charisma modifier to Eldritch Blast damage."],["Lessons of the First Ones","Invocation","Grants one Origin feat; taken as Magic Initiate (Cleric)."],["Pact of the Chain","Invocation","Cast Find Familiar as a Magic action without a slot; the familiar can attack on your Attack action."],["Pact Magic","Warlock","Two spell slots that recover on a rest."],["Magical Cunning","Warlock","Once per long rest, regain up to 1 Pact slot after a one-minute rite."],["Healing Hands","Variant Aasimar","Once per long rest, touch a creature to restore 2 hit points."],["Celestial Resistance","Aasimar","Resistance to necrotic and radiant damage."],["Celestial Legacy","Aasimar","Know the Light cantrip; Charisma is the casting ability. Lesser Restoration at level 3, Daylight at level 5, once each per long rest."],["Darkvision","Species","See in the dark to 60 ft."],["Magic Initiate (Cleric)","Feat","Two Cleric cantrips (Sacred Flame, Spare the Dying) and one 1st-level spell (Guiding Bolt) castable once free per long rest, or with slots."]],
gear:{gp:15,items:[["Quarterstaff, +1",1],["Leather armor",1],["Dagger",2],["Sickle",1],["Chest",1],["Clothes, common",1],["Backpack",1],["Book",2],["Orb",1],["Crowbar",1],["Hammer",1],["Holy water (flask)",1],["Manacles",1],["Mirror, steel",1],["Oil (flask)",1],["Oil",10],["Tinderbox",2],["Torch",3],["Stake (wooden)",9],["Holy symbol",1],["Parchment",10],["Lamp",1],["Ink pen",1],["Ink",1],["Abacus of the Unbroken Ledger",1]]},
spells:{dc:13,atk:5,ab:"CHA",slots:2,slotLvl:1,
can:[["Eldritch Blast","Warlock","+5","1A","120 ft.","V,S","Instant"],["Chill Touch","Warlock","+5","1A","Touch","V,S","Instant"],["Sacred Flame","Magic Initiate","DEX 13","1A","60 ft.","V,S","Instant"],["Spare the Dying","Magic Initiate","-","1A","15 ft.","V,S","Instant"],["Light","Celestial Legacy","DEX 13","1A","Touch","V,M","1 hour"]],
l1:[["Hex","Warlock","-","1 BA","90 ft.","V,S,M","Conc., 1 hour"],["Protection from Evil and Good","Warlock","-","1A","Touch","V,S,M","Conc., 10 min"],["Hellish Rebuke","Warlock","DEX 13","1R","60 ft.","V,S","Instant"],["Guiding Bolt","Magic Initiate","+5","1A","120 ft.","V,S","1 round"],["Find Familiar","Invocation (ritual)","-","1A","10 ft.","V,S,M","Instant"]]},
story:{gender:"Male",age:38,size:"Medium",height:"6'8\"",weight:"180 lb",align:"Lawful Evil",faith:"Jergal, the Lord of the End of Everything",skin:"Blue",eyes:"Black/blue",hair:"Flowing dark",
traits:"I never speak of the pact that binds me and I do not distribute my capital for free.",ideals:"I'm a monster that destroys other monsters, and anything else that gets in my way. (Evil)",bonds:"I record every transaction, curse, and cosmic anomaly in my ledger. This ledger is my legacy.",flaws:"I talk to spirits that no one else can see.",
allies:"The Invisible Auditor, a spiteful invisible fiend familiar bound to Malakor's contract, scouts ahead and doubles as a sounding board.\nThe Scribes of the Unbroken Ledger (Jergal): an employment contract with an underworld entity tasked with auditing the living and the dead.",
backstory:"I. The Auditing of Flesh\nBefore the shadow touched him, Malakor Vane was a senior clerk and estate liquidator for a corrupt mercantile syndicate, itemizing the assets of the dead. He learned that people are temporary but the ledger is eternal. While auditing the estate of a scholar who died in strange circumstances, he found a hidden second ledger tracking souls and cosmic debts, and the shadows around his desk began to breathe.\n\nII. The Scribe's Audit\nMalakor did not scream. He saw the systemic beauty in it: the cosmos runs on a balance sheet, and its ultimate accountant is Jergal, the dispassionate Scribe of the Dead, who wanted an agent to do the field work. Jergal revealed a centuries-old deficit: a kingdom behind a wall of fog, ruled by a tyrant, Strahd von Zarovich, who has hoarded souls and cheated death. Malakor was offered the raw magic of the Undead in exchange for balancing the books.\n\nIII. Entry into the Mists\nMalakor treats Barovia as a bankrupt enterprise waiting to be liquidated and his companions as valuable front-line assets whose survival must be managed.",
notes:"Modus operandi: completely transactional. He will fiercely protect party members as assets. If a choice doesn't maximize efficiency or bring him closer to balancing Strahd's debt, he will coldly advocate against it. Everything has a price."}}},
{slug:"lysander",name:"Lysander Vale",portrait_path:"images/lysander.jpg",own:null,live:{},
sheet:{header:{cls:"Bard",species:"Half-elf",player:"Jonny"},story:{backstory:"Handsome but weary, with shoulder-length dark brown hair streaked with silver and piercing silver eyes. He carries a lute engraved with roses and ravens and a cracked red leather journal, and he is chasing the mystery of a family debt that reaches Strahd."}}},
{slug:"alaric",name:"Sir Alaric Thorne",portrait_path:"images/alaric.jpg",own:null,live:{},
sheet:{header:{cls:"Paladin (Oath of Vengeance)",species:"Human",bg:"Haunted One",player:"Aaron"},story:{backstory:"A blacksmith's son who hid beneath the forge while monsters killed his family. After a spared vampire spawn escaped and killed again, he swore an oath to finish evil without hesitation and has hunted the undead ever since.",ideals:"Justice delayed is merely evil given time to grow."}}}
];
